usr: fix ss-tun reworked script diff merge problem

diff --git a/assets/configs/usr/local/bin/ss-tun b/assets/configs/usr/local/bin/ss-tun
--- a/assets/configs/usr/local/bin/ss-tun
+++ b/assets/configs/usr/local/bin/ss-tun
@@ -1,14 +1,12 @@
 #!/usr/bin/env sh
 
-if [ $# -ne 1 ] && ! test -f "$1"; then
-  echo "Usage: $0 <shadowocks_config_path>"
+# Root check
+if [ "$(id -u)" -ne 0 ]; then
+  echo "This script must be run as root." >&2
   exit 1
 fi
 
-SHADOWSOCKS_CONFIG_PATH="$1"
-SHADOWSOCKS_CONFIG="$(cat "$SHADOWSOCKS_CONFIG_PATH")"
-
-trap destroy HUP INT
+SSLOCAL_PID_FILE="/opt/ss-tun/sslocal.pid"
 
 config() {
   key="$1"
@@ -16,77 +14,66 @@ config() {
 }
 
 prepare() {
-  ip tuntap del name "$(config tun_interface_name)" mode tun 2>/dev/null || true
+
+  mkdir -p $(dirname "$SSLOCAL_PID_FILE")
+
+  # Create tuntap device (leave as-is if present)
+  ip tuntap add name "$(config tun_interface_name)" mode tun 2>/dev/null || true
 }
 
-create() {
+disconnect() {
+  test -f "$SSLOCAL_PID_FILE" && {
+    kill -INT $(cat "$SSLOCAL_PID_FILE")
+    rm "$SSLOCAL_PID_FILE"
+  }
 
-  prepare
-
-  # Create TUN interface
-  ip tuntap add name "$(config tun_interface_name)" mode tun
-  ip link set up dev "$(config tun_interface_name)"
-  ip addr add "$(config tun_interface_address)" dev "$(config tun_interface_name)"
-
-  server_ip="$(config "server")"
-
-  # Get default details (to exclude packets to server from looping)
-  defaults="$(ip -j route | jq '.[] | select(.dst=="default")')"
-  default_iface="$(echo "$defaults" | jq -r .dev)"
-  default_gateway="$(echo "$defaults" | jq -r .gateway)"
-  ip route add "$server_ip" via "$default_gateway" dev "$default_iface" metric 100
-
-  # Exclude DNS server(s) from tunnel
-  grep '^nameserver' /etc/resolv.conf | awk '{print $2}' |
-    while IFS= read -r dns_ip; do
-      ip route add "$dns_ip" via "$default_gateway" dev "$default_iface" metric 100
-    done
-
-  # Set TUN device as default with a higher metric
-  ip route add default dev "$(config tun_interface_name)" metric 100
-
-}
-
-destroy() {
-
-  # Delete default route via TUN interface
-  ip route del default dev "$(config tun_interface_name)"
-
-  # Delete routes to DNS servers via default gateway
-  grep '^nameserver' /etc/resolv.conf | awk '{print $2}' |
-    while IFS= read -r dns_ip; do
-      ip route del "$dns_ip"
-    done
-
-  # Delete route to server via default gateway
-  server_ip="$(config server)"
-  ip route del "$server_ip"
-
-  # Set link to down
-  ip link set down dev "$(config tun_interface_name)"
-
-  # Clean up TUN interface
-  ip addr del "$(config tun_interface_address)" dev "$(config tun_interface_name)"
-  ip tuntap del name "$(config tun_interface_name)" mode tun
 }
 
 connect() {
 
-  sslocal -s "$(config server):$(config server_port)" \
+  prepare
+
+  sslocal \
+    -s "$(config server):$(config server_port)" \
     -k "$(config password)" \
     -m "$(config method)" \
     --protocol tun \
     --tcp-fast-open \
     --tun-interface-name "$(config tun_interface_name)" \
-    --tun-interface-address "$(config tun_interface_address)"
-
-  # sslocal -c "$SHADOWSOCKS_CONFIG_PATH"
-
+    --tun-interface-address "$(config tun_interface_address)" \
+    --outbound-bind-interface "$OUTBOUND_BIND_INTERFACE" \
+    --daemonize \
+    --daemonize-pid "$SSLOCAL_PID_FILE"
 }
 
-main() {
-  create
+# POSIX argument parsing
+case "$1" in
+-c)
+  # Connect requires 2 additional arguments
+  if [ $# -ne 3 ]; then
+    echo "Error: -c requires a config path and a bind interface." >&2
+    exit 1
+  fi
+
+  SHADOWSOCKS_CONFIG_PATH="$2"
+  OUTBOUND_BIND_INTERFACE="$3"
+
+  if [ ! -r "$SHADOWSOCKS_CONFIG_PATH" ] || [ -z "$OUTBOUND_BIND_INTERFACE" ]; then
+    echo "Error: Config file not found or not readable at '$SHADOWSOCKS_CONFIG_PATH'" >&2
+    exit 1
+  fi
+
+  SHADOWSOCKS_CONFIG="$(cat "$SHADOWSOCKS_CONFIG_PATH")"
+
+  disconnect
   connect
-}
-
-main
+  ;;
+-d)
+  disconnect
+  exit 0
+  ;;
+*)
+  echo "Error: Unknown option" >&2
+  exit 1
+  ;;
+esac
